name: sumup_example
description: Demonstrates how to use the sumup plugin.

publish_to: 'none' 

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  sumup:
    path: ../ 
 
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false
